const Pokemon = [
    {
        key: 0,
        id: 1,
        name: "Bulbasaur",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/001Bulbasaur.webp",
        stats: [45, 49, 49, 65, 65, 45, 318],
        dexEntry: "It can go for days without eating a single morsel. In the bulb on its back, it stores energy.",
        cry: "./cries/bulbasaur.mp3",
        abilities: ["Overgrow", "Chlorophyll"],
        sprite: "./img/Sprites/bulbasaur.png"
    },
    {
        key: 1,
        id: 2,
        name: "Ivysaur",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/002Ivysaur.webp",
        stats: [60, 62, 63, 80, 80, 60, 405],
        dexEntry: "The bud on its back grows by drawing energy. It gives off an aroma when it is ready to bloom.",
        cry: "./cries/ivysaur.mp3",
        abilities: ["Overgrow", "Chlorophyll"],
        sprite: "./img/Sprites/ivysaur.png"
    },
    {
        key: 2,
        id: 3,
        name: "Venusaur",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/003Venusaur.png",
        stats: [80, 82, 83, 100, 100, 80, 525],
        dexEntry: "The flower on its back catches the sun's rays. The sunlight is then absorbed and used for energy.",
        cry: "./cries/venusaur.mp3",
        abilities: ["Overgrow", "Chlorophyll"],
        sprite: "./img/Sprites/venusaur.png",
        hasVariant: true
    },
    {
        key: 3,
        id: 4,
        name: "Charmander",
        types: ["Fire"],
        img: "./img/Pokemon/004Charmander.png",
        stats: [39, 52, 43, 60, 50, 66, 309],
        dexEntry: "The flame at the tip of its tail makes a sound as it burns. You can only hear it in quiet places.",
        cry: "./cries/charmander.mp3",
        abilities: ["Blaze", "Solar Power"],
        sprite: "./img/Sprites/charmander.png"
    },
    {
        key: 4,
        id: 5,
        name: "Charmeleon",
        types: ["Fire"],
        img: "./img/Pokemon/005Charmeleon.png",
        stats: [58, 64, 58, 80, 65, 80, 405],
        dexEntry: "Tough fights could excite this Pokémon. When excited, it may breathe out bluish-white flames.",
        cry: "./cries/charmeleon.mp3",
        abilities: ["Blaze", "Solar Power"],
        sprite: "./img/Sprites/charmeleon.png"
    },
    {
        key: 5,
        id: 6,
        name: "Charizard",
        types: ["Fire", "Flying"],
        img: "./img/Pokemon/006Charizard.webp",
        stats: [78, 84, 78, 109, 85, 100, 534],
        dexEntry: "	When this Pokémon expels a blast of superhot fire, the red flame at the tip of its tails burns more intensely.",
        cry: "./cries/charizard.mp3",
        abilities: ["Blaze", "Solar Power"],
        sprite: "./img/Sprites/charizard.png",
        hasVariant: true
    },
    {
        key: 6,
        id: 7,
        name: "Squirtle",
        types: ["Water"],
        img: "./img/Pokemon/007Squirtle.png",
        stats: [44, 48, 65, 50, 64, 43, 314],
        dexEntry: "Shoots water at prey while in the water. Withdraws into its shell when in danger.",
        cry: "./cries/squirtle.mp3",
        abilities: ["Torrent", "Rain Dish"],
        sprite: "./img/Sprites/squirtle.png"
    },
    {
        key: 7,
        id: 8,
        name: "Wartortle",
        types: ["Water"],
        img: "./img/Pokemon/008Wartortle.png",
        stats: [59, 63, 80, 65, 80, 58, 405],
        dexEntry: "When tapped on its head, this Pokémon will pull it in, but its tail will stick out a little bit.",
        cry: "./cries/wartortle.mp3",
        abilities: ["Torrent", "Rain Dish"],
        sprite: "./img/Sprites/wartortle.png"
    },
    {
        key: 8,
        id: 9,
        name: "Blastoise",
        types: ["Water"],
        img: "./img/Pokemon/009Blastoise.webp",
        stats: [79, 83, 100, 85, 105, 78, 530],
        dexEntry: "Once it takes aim at its enemy, it blasts out water with even more force than a fire hose.",
        cry: "./cries/blastoise.mp3",
        abilities: ["Torrent", "Rain Dish"],
        sprite: "./img/Sprites/blastoise.png",
        hasVariant: true
    },
    {
        key: 9,
        id: 10,
        name: "Caterpie",
        types: ["Bug"],
        img: "./img/Pokemon/010Caterpie.png",
        stats: [45, 30, 35, 20, 20, 45, 195],
        dexEntry: "If you touch the feeler on top of its head, it will release a horrible stink to protect itself.",
        cry: "./cries/caterpie.mp3",
        abilities: ["Shield Dust", "Run Away"],
        sprite: "./img/Sprites/caterpie.png"
    },
    {
        key: 10,
        id: 11,
        name: "Metapod",
        types: ["Bug"],
        img: "./img/Pokemon/011Metapod.webp",
        stats: [50, 20, 55, 25, 25, 30, 205],
        dexEntry: "Hardens its shell to protect itself. However, a large impact may cause it to pop out of its shell.",
        cry: "./cries/metapod.mp3",
        abilities: ["Shed Skin"],
        sprite: "./img/Sprites/metapod.png"
    },
    {
        key: 11,
        id: 12,
        name: "Butterfree",
        types: ["Bug", "Flying"],
        img: "./img/Pokemon/012Butterfree.webp",
        stats: [60, 45, 50, 80, 80, 70, 385],
        dexEntry: "Its wings, covered with poisonous powder, repel water. This allows it to fly in the rain.",
        cry: "./cries/butterfree.mp3",
        abilities: ["Compound Eyes", "Tinted Lens"],
        sprite: "./img/Sprites/butterfree.png",
        hasVariant: true
    },
    {
        key: 12,
        id: 13,
        name: "Weedle",
        types: ["Bug"],
        img: "./img/Pokemon/013Weedle.png",
        stats: [40, 35, 30, 20, 20, 50, 195],
        dexEntry: "Beware of the sharp stinger on its head. It hides in grass and bushes where it eats leaves.",
        cry: "./cries/weedle.mp3",
        abilities: ["Shield Dust", "Run Away"],
        sprite: "./img/Sprites/weedle.png"
    },
    {
        key: 13,
        id: 14,
        name: "Kakuna",
        types: ["Bug"],
        img: "./img/Pokemon/014Kakuna.png",
        stats: [45, 25, 50, 25, 25, 35, 205],
        dexEntry: "Able to move only slightly. When endangered, it may stick out its stinger and poison its enemy.",
        cry: "./cries/kakuna.mp3",
        abilities: ["Shed Skin"],
        sprite: "./img/Sprites/kakuna.png"
    },
    {
        key: 14,
        id: 15,
        name: "Beedrill",
        types: ["Bug", "Poison"],
        img: "./img/Pokemon/015Beedrill.webp",
        stats: [65, 90, 40, 45, 80, 75, 395],
        dexEntry: "It has three poisonous stingers on its forelegs and its tail. They are used to jab its enemy repeatedly.",
        cry: "./cries/beedrill.mp3",
        abilities: ["Swarm", "Sniper"],
        sprite: "./img/Sprites/beedrill.png",
        hasVariant: true
    },
    {
        key: 15,
        id: 16,
        name: "Pidgey",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/016Pidgey.png",
        stats: [40, 45, 40, 35, 35, 56, 251],
        dexEntry: "Very docile. If attacked, it will often kick up sand to protect itself rather than fight back.",
        cry: "./cries/pidgey.mp3",
        abilities: ["Keen Eye", "Tangled Feet", "Big Pecks"],
        sprite: "./img/Sprites/pidgey.png"
    },
    {
        key: 16,
        id: 17,
        name: "Pidgeotto",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/017Pidgeotto.png",
        stats: [63, 60, 55, 50, 50, 71, 349],
        dexEntry: "This Pokémon is full of vitality. It constantly flies around its large territory in search of prey.",
        cry: "./cries/pidgeotto.mp3",
        abilities: ["Keen Eye", "Tangled Feet", "Big Pecks"],
        sprite: "./img/Sprites/pidgeotto.png"
    },
    {
        key: 17,
        id: 18,
        name: "Pidgeot",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/018Pidgeot.png",
        stats: [83, 80, 75, 70, 70, 91, 469],
        dexEntry: "This Pokémon flies at Mach 2 speed, seeking prey. Its large talons are feared as wicked weapons.",
        cry: "./cries/pidgeot.mp3",
        abilities: ["Keen Eye", "Tangled Feet", "Big Pecks"],
        sprite: "./img/Sprites/pidgeot.png",
        hasVariant: true
    },
    {
        key: 18,
        id: 19,
        name: "Rattata",
        types: ["Normal"],
        img: "./img/Pokemon/019Rattata.png",
        stats: [30, 56, 35, 25, 35, 72, 253],
        dexEntry: "Will chew on anything with its fangs. If you see one, you can be certain that 40 more live in the area.",
        cry: "./cries/rattata.mp3",
        abilities: ["Run Away", "Guts", "Hustle"],
        sprite: "./img/Sprites/rattata.png",
        hasVariant: true
    },
    {
        key: 19,
        id: 20,
        name: "Raticate",
        types: ["Normal"],
        img: "./img/Pokemon/020Raticate.png",
        stats: [55, 81, 60, 50, 70, 97, 413],
        dexEntry: "Its hind feet are webbed. They act as flippers, so it can swim in rivers and hunt for prey.",
        cry: "./cries/raticate.mp3",
        abilities: ["Run Away", "Guts", "Hustle"],
        sprite: "./img/Sprites/raticate.png",
        hasVariant: true
    },
    {
        key: 20,
        id: 21,
        name: "Spearow",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/021Spearow.png",
        stats: [40, 60, 30, 31, 31, 70, 262],
        dexEntry: "Inept at flying high. However, it can fly around very fast to protect its territory.",
        cry: "./cries/spearow.mp3",
        abilities: ["Keen Eye", "Sniper"],
        sprite: "./img/Sprites/spearow.png"
    },
    {
        key: 21,
        id: 22,
        name: "Fearow",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/022Fearow.png",
        stats: [65, 90, 65, 61, 61, 100, 442],
        dexEntry: "A Pokémon that dates back many years. If it senses danger, it flies high and away, instantly.",
        cry: "./cries/fearow.mp3",
        abilities: ["Keen Eye", "Sniper"],
        sprite: "./img/Sprites/fearow.png"
    },
    {
        key: 22,
        id: 23,
        name: "Ekans",
        types: ["Poison"],
        img: "./img/Pokemon/023Ekans.png",
        stats: [35, 60, 44, 40, 54, 55, 288],
        dexEntry: "The older it gets, the longer it grows. At night, it wraps its long body around tree branches to rest.",
        cry: "./cries/ekans.mp3",
        abilities: ["Intimidate", "Shed Skin", "Unnerve"],
        sprite: "./img/Sprites/ekans.png"
    },
    {
        key: 23,
        id: 24,
        name: "Arbok",
        types: ["Poison"],
        img: "./img/Pokemon/024Arbok.png",
        stats: [60, 85, 69, 65, 79, 80, 438],
        dexEntry: "The frightening patterns on its belly have been studied. Six variations have been confirmed.",
        cry: "./cries/arbok.mp3",
        abilities: ["Intimidate", "Shed Skin", "Unnerve"],
        sprite: "./img/Sprites/arbok.png"
    },
    {
        key: 24,
        id: 25,
        name: "Pikachu",
        types: ["Electric"],
        img: "./img/Pokemon/025Pikachu.png",
        stats: [35, 55, 30, 50, 40, 90, 300],
        dexEntry: "This forest-dwelling Pokémon stores electricity in its cheeks, so you'll feel a tingly shock if you touch it.",
        cry: "./cries/pikachu.mp3",
        abilities: ["Static", "Lightning Rod"],
        sprite: "./img/Sprites/pikachu.png",
        hasVariant: true
    },
    {
        key: 25,
        id: 26,
        name: "Raichu",
        types: ["Electric"],
        img: "./img/Pokemon/026Raichu.png",
        stats: [60, 90, 55, 90, 80, 100, 475],
        dexEntry: "When electricity builds up inside its body, it becomes feisty. It also glows in the dark.",
        cry: "./cries/raichu.mp3",
        abilities: ["Static", "Lightning Rod"],
        sprite: "./img/Sprites/raichu.png",
        hasVariant: true
    },
    {
        key: 26,
        id: 27,
        name: "Sandshrew",
        types: ["Ground"],
        img: "./img/Pokemon/027Sandshrew.png",
        stats: [50, 75, 85, 20, 30, 40, 300],
        dexEntry: "Its body is dry. When it gets cold at night, its hide is said to become coated with a fine dew.",
        cry: "./cries/sandshrew.mp3",
        abilities: ["Sand Veil", "Sand Rush"],
        sprite: "./img/Sprites/sandshrew.png",
        hasVariant: true
    },
    {
        key: 27,
        id: 28,
        name: "Sandslash",
        types: ["Ground"],
        img: "./img/Pokemon/028Sandslash.png",
        stats: [75, 100, 110, 45, 55, 65, 450],
        dexEntry: "It is skilled at slashing enemies with its claws. If broken, they start to grow back in a day.",
        cry: "./cries/sandslash.mp3",
        abilities: ["Sand Veil", "Sand Rush"],
        sprite: "./img/Sprites/sandslash.png",
        hasVariant: true
    },
    {
        key: 28,
        id: 29,
        name: "Nidoran-F",
        types: ["Poison"],
        img: "./img/Pokemon/029Nidoran.png",
        stats: [55, 47, 52, 40, 40, 41, 275],
        dexEntry: "A mild-mannered Pokémon that does not like to fight. Beware–its small horn secretes venom.",
        cry: "./cries/nidoranf.mp3",
        abilities: ["Poison Point", "Rivalry", "Hustle"],
        sprite: "./img/Sprites/nidoran-f.png"
    },
    {
        key: 29,
        id: 30,
        name: "Nidorina",
        types: ["Poison"],
        img: "./img/Pokemon/030Nidorina.png",
        stats: [70, 62, 67, 55, 55, 56, 365],
        dexEntry: "When resting deep in its burrow, its barbs always retract. This is proof that it is relaxed.",
        cry: "./cries/nidorina.mp3",
        abilities: ["Poison Point", "Rivalry", "Hustle"],
        sprite: "./img/Sprites/nidorina.png"
    },
    {
        key: 30,
        id: 31,
        name: "Nidoqueen",
        types: ["Poison", "Ground"],
        img: "./img/Pokemon/031Nidoqueen.png",
        stats: [90, 92, 87, 75, 85, 76, 505],
        dexEntry: "Tough scales cover the sturdy body of this Pokémon. It appears that the scales grow in cycles.",
        cry: "./cries/nidoqueen.mp3",
        abilities: ["Poison Point", "Rivalry", "Sheer Force"],
        sprite: "./img/Sprites/nidoqueen.png"
    },
    {
        key: 31,
        id: 32,
        name: "Nidoran-M",
        types: ["Poison"],
        img: "./img/Pokemon/032Nidoran.webp",
        stats: [46, 57, 40, 40, 40, 50, 273],
        dexEntry: "Its large ears are always kept upright. If it senses danger, it will attack with a poisonous sting.",
        cry: "./cries/nidoranm.mp3",
        abilities: ["Poison Point", "Rivalry", "Hustle"],
        sprite: "./img/Sprites/nidoran-m.png"
    },
    {
        key: 32,
        id: 33,
        name: "Nidorino",
        types: ["Poison"],
        img: "./img/Pokemon/033Nidorino.png",
        stats: [61, 72, 57, 55, 55, 65, 365],
        dexEntry: ["Poison Point", "Rivalry", "Hustle"],
        cry: "./cries/nidorino.mp3",
        abilities: ["Poison Point", "Rivalry", "Hustle"],
        sprite: "./img/Sprites/nidorino.png"
    },
    {
        key: 33,
        id: 34,
        name: "Nidoking",
        types: ["Poison", "Ground"],
        img: "./img/Pokemon/034Nidoking.webp",
        stats: [81, 102, 77, 85, 75, 85, 505],
        dexEntry: "Its steel-like hide adds to its powerful tackle. Its horns are so hard, they can pierce a diamond.",
        cry: "./cries/nidoking.mp3",
        abilities: ["Poison Point", "Rivalry", "Sheer Force"],
        sprite: "./img/Sprites/nidoking.png"
    },

    {
        key: 34,
        id: 35,
        name: "Clefairy",
        types: ["Fairy"],
        img: "./img/Pokemon/035Clefairy.webp",
        stats: [70, 45, 48, 60, 65, 35, 323],
        dexEntry: "Adored for their cute looks and playfulness. They are thought to be rare, as they do not appear often.",
        cry: "./cries/clefairy.mp3",
        abilities: ["Cute Charm", "Magic Guard", "Friend Guard"],
        sprite: "./img/Sprites/clefairy.png"
    },{
        key: 35,
        id: 36,
        name: "Clefable",
        types: ["Fairy"],
        img: "./img/Pokemon/036Clefable.webp",
        stats: [70, 62, 63, 80, 80, 60, 405],
        dexEntry: "They appear to be very protective of their own world. It is a kind of fairy, rarely seen by people.",
        cry: "./cries/clefable.mp3",
        abilities: ["Cute Charm", "Magic Guard", "Unaware"],
        sprite: "./img/Sprites/clefable.png"
    },
    {
        key: 36,
        id: 37,
        name: "Vulpix",
        types: ["Fire"],
        img: "./img/Pokemon/037Vulpix.webp",
        stats: [38, 41, 40, 50, 65, 65, 299],
        dexEntry: "Both its fur and its tails are beautiful. As it grows, the tails split and form more tails.",
        cry: "./cries/vulpix.mp3",
        abilities: ["Flash Fire", "Drought"],
        sprite: "./img/Sprites/vulpix.png",
        hasVariant: true
    },
    {
        key: 37,
        id: 38,
        name: "Ninetales",
        types: ["Fire"],
        img: "./img/Pokemon/038Ninetales.webp",
        stats: [73, 76, 75, 81, 100, 100, 505],
        dexEntry: "According to an enduring legend, nine noble saints were united and reincarnated as this Pokémon.",
        cry: "./cries/ninetales.mp3",
        abilities: ["Flash Fire", "Drought"],
        sprite: "./img/Sprites/ninetales.png",
        hasVariant: true
    },
    {
        key: 38,
        id: 39,
        name: "Jigglypuff",
        types: ["Normal", "Fairy"],
        img: "./img/Pokemon/039Jigglypuff.webp",
        stats: [115, 45, 20, 45, 25, 20, 270],
        dexEntry: "Uses its cute round eyes to enrapture its foe. It then sings a pleasing melody that lulls the foe to sleep.",
        cry: "./cries/jigglypuff.mp3",
        abilities: ["Cute Charm", "Competitive", "Friend Guard"],
        sprite: "./img/Sprites/jigglypuff.png"
    },
    {
        key: 39,
        id: 40,
        name: "Wigglytuff",
        types: ["Normal", "Fairy"],
        img: "./img/Pokemon/040Wigglytuff.webp",
        stats: [140, 70, 45, 85, 50, 45, 435],
        dexEntry: "Its body is very elastic. By inhaling deeply, it can continue to inflate itself without limit.",
        cry: "./cries/wigglytuff.mp3",
        abilities: ["Cute Charm", "Competitive", "Frisk"],
        sprite: "./img/Sprites/wigglytuff.png"
    },
    {
        key: 40,
        id: 41,
        name: "Zubat",
        types: ["Poison", "Flying"],
        img: "./img/Pokemon/041Zubat.webp",
        stats: [40, 45, 35, 30, 40, 55, 245],
        dexEntry: "Emits ultrasonic cries while it flies. They act as a sonar used to check for objects in its way.",
        cry: "./cries/zubat.mp3",
        abilities: ["Inner Focus", "Infiltrator"],
        sprite: "./img/Sprites/zubat.png"
    },
    {
        key: 41,
        id: 42,
        name: "Golbat",
        types: ["Poison", "Flying"],
        img: "./img/Pokemon/042Golbat.webp",
        stats: [75, 80, 70, 65, 75, 90, 455],
        dexEntry: "It attacks in a stealthy manner, without warning. Its sharp fangs are used to bite and to suck blood.",
        cry: "./cries/golbat.mp3",
        abilities: ["Inner Focus", "Infiltrator"],
        sprite: "./img/Sprites/golbat.png"
    },
    {
        key: 42,
        id: 43,
        name: "Oddish",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/043Oddish.webp",
        stats: [45, 50, 55, 75, 65, 30, 320],
        dexEntry: "It may be mistaken for a clump of weeds. If you try to yank it out of the ground, it shrieks horribly.",
        cry: "./cries/oddish.mp3",
        abilities: ["Chlorophyll", "Run Away"],
        sprite: "./img/Sprites/oddish.png"
    },
    {
        key: 43,
        id: 44,
        name: "Gloom",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/044Gloom.webp",
        stats: [60, 65, 70, 85, 75, 40, 395],
        dexEntry: "Smells incredibly foul! However, around one out of a thousand people enjoy sniffing its nose-bending stink.",
        cry: "./cries/gloom.mp3",
        abilities: ["Chlorophyll", "Stench"],
        sprite: "./img/Sprites/gloom.png"
    },
    {
        key: 44,
        id: 45,
        name: "Vileplume",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/045Vileplume.webp",
        stats: [75, 80, 85, 100, 90, 50, 480],
        dexEntry: "Flaps its broad flower petals to scatter its poisonous pollen. The flapping sound is very loud.",
        cry: "./cries/vileplume.mp3",
        abilities: ["Chlorophyll", "Effect Spore"],
        sprite: "./img/Sprites/vileplume.png"
    },
    {
        key: 45,
        id: 46,
        name: "Paras",
        types: ["Bug", "Grass"],
        img: "./img/Pokemon/046Paras.webp",
        stats: [35, 70, 55, 45, 55, 25, 285],
        dexEntry: "Burrows under the ground to gnaw on tree roots. The mushrooms on its back absorb most of the nutrition.",
        cry: "./cries/paras.mp3",
        abilities: ["Effect Spore", "Dry Skin", "Damp"],
        sprite: "./img/Sprites/paras.png"
    },
    {
        key: 46,
        id: 47,
        name: "Parasect",
        types: ["Bug", "Grass"],
        img: "./img/Pokemon/047Parasect.png",
        stats: [60, 95, 80, 60, 80, 30, 405],
        dexEntry: "The bug host is drained of energy by the mushrooms on its back. The mushroom appears to do all the thinking.",
        cry: "./cries/parasect.mp3",
        abilities: ["Effect Spore", "Dry Skin", "Damp"],
        sprite: "./img/Sprites/parasect.png"
    },
    {
        key: 47,
        id: 48,
        name: "Venonat",
        types: ["Bug", "Poison"],
        img: "./img/Pokemon/048Venonat.png",
        stats: [60, 55, 50, 40, 55, 45, 305],
        dexEntry: "Its large eyes act as a radar. In a bright place, you can see that they are clusters of many tiny eyes.",
        cry: "./cries/venonat.mp3",
        abilities: ["Compound Eyes", "Tinted Lens", "Run Away"],
        sprite: "./img/Sprites/venonat.png"
    },
    {
        key: 48,
        id: 49,
        name: "Venomoth",
        types: ["Bug", "Poison"],
        img: "./img/Pokemon/049Venomoth.png",
        stats: [70, 65, 60, 90, 75, 90, 450],
        dexEntry: "The powdery scales on its wings are hard to remove from skin. They also contain poison that leaks out on contact.",
        cry: "./cries/venomoth.mp3",
        abilities: ["Shield Dust", "Tinted Lens", "Wonder Skin"],
        sprite: "./img/Sprites/venomoth.png"
    },
    {
        key: 49,
        id: 50,
        name: "Diglett",
        types: ["Ground"],
        img: "./img/Pokemon/050Diglett.webp",
        stats: [10, 55, 25, 35, 45, 95, 265],
        dexEntry: "It prefers dark places. It spends most of its time underground, though it may pop up in caves.",
        cry: "./cries/diglett.mp3",
        abilities: ["Sand Veil", "Arena Trap", "Sand Force"],
        sprite: "./img/Sprites/diglett.png",
        hasVariant: true
    },
    {
        key: 50,
        id: 51,
        name: "Dugtrio",
        types: ["Ground"],
        img: "./img/Pokemon/051Dugtrio.webp",
        stats: [30, 100, 50, 50, 70, 120, 425],
        dexEntry: "A team of triplets that can burrow to a depth of 60 miles. It's reported that this triggers an earthquake.",
        cry: "./cries/dugtrio.mp3",
        abilities: ["Sand Veil", "Arena Trap", "Sand Force"],
        sprite: "./img/Sprites/dugtrio.png",
        hasVariant: true
    },
    {
        key: 51,
        id: 52,
        name: "Meowth",
        types: ["Normal"],
        img: "./img/Pokemon/052Meowth.webp",
        stats: [40, 45, 35, 40, 40, 90, 290],
        dexEntry: "Appears to be more active at night. It loves round and shiny things. It can't stop itself from picking them up.",
        cry: "./cries/meowth.mp3",
        abilities: ["Pickup", "Technician", "Unnerve"],
        sprite: "./img/Sprites/meowth.png",
        hasVariant: true
    },
    {
        key: 52,
        id: 53,
        name: "Persian",
        types: ["Normal"],
        img: "./img/Pokemon/053Persian.webp",
        stats: [65, 70, 60, 65, 65, 115, 440],
        dexEntry: "The gem in its forehead glows on its own! It walks with all the grace and elegance of a proud queen.",
        cry: "./cries/persian.mp3",
        abilities: ["Limber", "Technician", "Unnerve"],
        sprite: "./img/Sprites/persian.png",
        hasVariant: true
    },
    {
        key: 53,
        id: 54,
        name: "Psyduck",
        types: ["Water"],
        img: "./img/Pokemon/054Psyduck.webp",
        stats: [50, 52, 48, 65, 50, 55, 320],
        dexEntry: "Always tormented by headaches. It uses psychic powers, but whether it intends to do so is not known.",
        cry: "./cries/psyduck.mp3",
        abilities: ["Damp", "Cloud Nine", "Swift Swim"],
        sprite: "./img/Sprites/psyduck.png"
    },
    {
        key: 54,
        id: 55,
        name: "Golduck",
        types: ["Water"],
        img: "./img/Pokemon/055Golduck.webp",
        stats: [80, 82, 78, 95, 80, 85, 500],
        dexEntry: "Its long, slim limbs end in broad flippers. They are used for swimming gracefully in lakes.",
        cry: "./cries/golduck.mp3",
        abilities: ["Damp", "Cloud Nine", "Swift Swim"],
        sprite: "./img/Sprites/golduck.png"
    },
    {
        key: 55,
        id: 56,
        name: "Mankey",
        types: ["Fighting"],
        img: "./img/Pokemon/056Mankey.webp",
        stats: [40, 80, 35, 35, 45, 70, 305],
        dexEntry: "An agile Pokémon that lives in trees. It angers easily and will not hesitate to attack anything.",
        cry: "./cries/mankey.mp3",
        abilities: ["Vital Spirit", "Anger Point", "Defiant"],
        sprite: "./img/Sprites/mankey.png"
    },
    {
        key: 56,
        id: 57,
        name: "Primeape",
        types: ["Fighting"],
        img: "./img/Pokemon/057Primeape.webp",
        stats: [65, 105, 60, 60, 70, 95, 455],
        dexEntry: "It stops being angry only when nobody else is around. To view this moment is very difficult.",
        cry: "./cries/primeape.mp3",
        abilities: ["Vital Spirit", "Anger Point", "Defiant"],
        sprite: "./img/Sprites/primeape.png"
    },
    {
        key: 57,
        id: 58,
        name: "Growlithe",
        types: ["Fire"],
        img: "./img/Pokemon/058Growlithe.webp",
        stats: [55, 70, 45, 70, 50, 60, 350],
        dexEntry: "A Pokémon with a friendly nature. However, it will bark fiercely at anything invading its territory.",
        cry: "./cries/growlithe.mp3",
        abilities: ["Intimidate", "Flash Fire", "Justified"],
        sprite: "./img/Sprites/growlithe.png"
    },
    {
        key: 58,
        id: 59,
        name: "Arcanine",
        types: ["Fire"],
        img: "./img/Pokemon/059Arcanine.webp",
        stats: [90, 110, 80, 100, 80, 95, 555],
        dexEntry: "A legendary Pokémon in the East. Many people are charmed by the grace and beauty of its running.",
        cry: "./cries/arcanine.mp3",
        abilities: ["Intimidate", "Flash Fire", "Justified"],
        sprite: "./img/Sprites/arcanine.png"
    },
    {
        key: 59,
        id: 60,
        name: "Poliwag",
        types: ["Water"],
        img: "./img/Pokemon/060Poliwag.webp",
        stats: [40, 50, 40, 40, 40, 90, 300],
        dexEntry: "The direction of the spiral on the belly differs by area. It is more adept at swimming than walking.",
        cry: "./cries/poliwag.mp3",
        abilities: ["Water Absorb", "Damp", "Swift Swim"],
        sprite: "./img/Sprites/poliwag.png"
    },
    {
        key: 60,
        id: 61,
        name: "Poliwhirl",
        types: ["Water"],
        img: "./img/Pokemon/061Poliwhirl.png",
        stats: [65, 65, 65, 50, 50, 90, 385],
        dexEntry: "Under attack, it uses its belly spiral to put the foe to sleep. It then makes its escape.",
        cry: "./cries/poliwhirl.mp3",
        abilities: ["Water Absorb", "Damp", "Swift Swim"],
        sprite: "./img/Sprites/poliwhirl.png"
    },
    {
        key: 61,
        id: 62,
        name: "Poliwrath",
        types: ["Water", "Fighting"],
        img: "./img/Pokemon/062Poliwrath.png",
        stats: [90, 85, 95, 70, 90, 70, 500],
        dexEntry: "Swims powerfully using all the muscles in its body. It can even overtake world-class swimmers.",
        cry: "./cries/poliwrath.mp3",
        abilities: ["Water Absorb", "Damp", "Swift Swim"],
        sprite: "./img/Sprites/poliwrath.png"
    },
    {
        key: 62,
        id: 63,
        name: "Abra",
        types: ["Psychic"],
        img: "./img/Pokemon/063Abra.webp",
        stats: [25, 20, 15, 105, 55, 90, 310],
        dexEntry: "Sleeps 18 hours a day. If it senses danger, it will teleport itself to safety even as it sleeps.",
        cry: "./cries/abra.mp3",
        abilities: ["Synchronize", "Inner Focus", "Magic Guard"],
        sprite: "./img/Sprites/abra.png"
    },
    {
        key: 63,
        id: 64,
        name: "Kadabra",
        types: ["Psychic"],
        img: "./img/Pokemon/064Kadabra.webp",
        stats: [40, 35, 30, 120, 70, 105, 400],
        dexEntry: "Many odd things happen if this Pokémon is close by. For example, it makes clocks run backward.",
        cry: "./cries/kadabra.mp3",
        abilities: ["Synchronize", "Inner Focus", "Magic Guard"],
        sprite: "./img/Sprites/kadabra.png"
    },
    {
        key: 64,
        id: 65,
        name: "Alakazam",
        types: ["Psychic"],
        img: "./img/Pokemon/065Alakazam.png",
        stats: [55, 50, 45, 135, 95, 120, 500],
        dexEntry: "A Pokémon that can memorize anything. It never forgets what it learns—that's why this Pokémon is smart.",
        cry: "./cries/alakazam.mp3",
        abilities: ["Synchronize", "Inner Focus", "Magic Guard"],
        sprite: "./img/Sprites/alakazam.png",
        hasVariant: true
    },
    {
        key: 65,
        id: 66,
        name: "Machop",
        types: ["Fighting"],
        img: "./img/Pokemon/066Machop.webp",
        stats: [70, 80, 50, 35, 35, 35, 305],
        dexEntry: "Very powerful in spite of its small size. Its mastery of many types of martial arts makes it very tough.",
        cry: "./cries/machop.mp3",
        abilities: ["Guts", "No Guard", "Steadfast"],
        sprite: "./img/Sprites/machop.png"
    },
    {
        key: 66,
        id: 67,
        name: "Machoke",
        types: ["Fighting"],
        img: "./img/Pokemon/067Machoke.png",
        stats: [80, 100, 70, 50, 60, 45, 405],
        dexEntry: "The belt around its waist holds back its energy. Without it, this Pokémon would be unstoppable.",
        cry: "./cries/machoke.mp3",
        abilities: ["Guts", "No Guard", "Steadfast"],
        sprite: "./img/Sprites/machoke.png"
    },
    {
        key: 67,
        id: 68,
        name: "Machamp",
        types: ["Fighting"],
        img: "./img/Pokemon/068Machamp.webp",
        stats: [90, 130, 80, 65, 85, 55, 505],
        dexEntry: "One arm alone can move mountains. Using all four arms, this Pokémon fires off awesome punches.",
        cry: "./cries/machamp.mp3",
        abilities: ["Guts", "No Guard", "Steadfast"],
        sprite: "./img/Sprites/machamp.png",
        hasVariant: true
    },
    {
        key: 68,
        id: 69,
        name: "Bellsprout",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/069Bellsprout.webp",
        stats: [50, 75, 35, 70, 30, 40, 300],
        dexEntry: "Prefers hot and humid places. It ensnares tiny bugs with its vines and devours them.",
        cry: "./cries/bellsprout.mp3",
        abilities: ["Chlorophyll", "Gluttony"],
        sprite: "./img/Sprites/bellsprout.png"
    },
    {
        key: 69,
        id: 70,
        name: "Weepinbell",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/070Weepinbell.webp",
        stats: [65, 90, 50, 85, 45, 55, 390],
        dexEntry: "When hungry, it swallows anything that moves. Its hapless prey is dissolved by strong acids.",
        cry: "./cries/weepinbell.mp3",
        abilities: ["Chlorophyll", "Gluttony"],
        sprite: "./img/Sprites/weepinbell.png"
    },
    {
        key: 70,
        id: 71,
        name: "Victreebel",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/071Victreebel.webp",
        stats: [80, 105, 65, 100, 70, 70, 490],
        dexEntry: "Lures prey with the sweet aroma of honey. Swallowed whole, the prey is dissolved in a day, bones and all.",
        cry: "./cries/victreebel.mp3",
        abilities: ["Chlorophyll", "Gluttony"],
        sprite: "./img/Sprites/victreebel.png"
    },
    {
        key: 71,
        id: 72,
        name: "Tentacool",
        types: ["Water", "Poison"],
        img: "./img/Pokemon/072Tentacool.png",
        stats: [40, 40, 35, 50, 100, 70, 335],
        dexEntry: "It can sometimes be found all dry and shriveled up on a beach. Toss it back into the sea to revive it.",
        cry: "./cries/tentacool.mp3",
        abilities: ["Clear Body", "Liquid Ooze", "Rain Dish"],
        sprite: "./img/Sprites/tentacool.png"
    },
    {
        key: 72,
        id: 73,
        name: "Tentacruel",
        types: ["Water", "Poison"],
        img: "./img/Pokemon/073Tentacruel.png",
        stats: [80, 70, 65, 80, 120, 100, 515],
        dexEntry: "	Its 80 tentacles can stretch and contract freely. They wrap around prey and weaken it with poison.",
        cry: "./cries/tentacruel.mp3",
        abilities: ["Clear Body", "Liquid Ooze", "Rain Dish"],
        sprite: "./img/Sprites/tentacruel.png"
    },
    {
        key: 73,
        id: 74,
        name: "Geodude",
        types: ["Rock", "Ground"],
        img: "./img/Pokemon/074Geodude.webp",
        stats: [40, 80, 100, 30, 30, 20, 300],
        dexEntry: "Commonly found near mountain trails and the like. If you step on one by accident, it gets angry.",
        cry: "./cries/geodude.mp3",
        abilities: ["Rock Head", "Sturdy", "Sand Veil"],
        sprite: "./img/Sprites/geodude.png",
        hasVariant: true
    },
    {
        key: 74,
        id: 75,
        name: "Graveler",
        types: ["Rock", "Ground"],
        img: "./img/Pokemon/075Graveler.webp",
        stats: [55, 95, 115, 45, 45, 35, 390],
        dexEntry: "Often seen rolling down mountain trails. Obstacles are just things to roll straight over, not avoid.",
        cry: "./cries/graveler.mp3",
        abilities: ["Rock Head", "Sturdy", "Sand Veil"],
        sprite: "./img/Sprites/graveler.png",
        hasVariant: true
    },
    {
        key: 75,
        id: 76,
        name: "Golem",
        types: ["Rock", "Ground"],
        img: "./img/Pokemon/076Golem.webp",
        stats: [80, 120, 130, 55, 65, 45, 495],
        dexEntry: "Once it sheds its skin, its body turns tender and whitish. Its hide hardens when it's exposed to air.",
        cry: "./cries/golem.mp3",
        abilities: ["Rock Head", "Sturdy", "Sand Veil"],
        sprite: "./img/Sprites/golem.png",
        hasVariant: true
    },
    {
        key: 76,
        id: 77,
        name: "Ponyta",
        types: ["Fire"],
        img: "./img/Pokemon/077Ponyta.webp",
        stats: [50, 85, 55, 65, 65, 90, 410],
        dexEntry: "	Capable of jumping incredibly high. Its hooves and sturdy legs absorb the impact of a hard landing.",
        cry: "./cries/ponyta.mp3",
        abilities: ["Run Away", "Flash Fire", "Flame Body"],
        sprite: "./img/Sprites/ponyta.png",
        hasVariant: true
    },
    {
        key: 77,
        id: 78,
        name: "Rapidash",
        types: ["Fire"],
        img: "./img/Pokemon/078Rapidash.webp",
        stats: [65, 100, 70, 80, 80, 105, 500],
        dexEntry: "Just loves to run. If it sees something faster than itself, it will give chase at top speed.",
        cry: "./cries/rapidash.mp3",
        abilities: ["Run Away", "Flash Fire", "Flame Body"],
        sprite: "./img/Sprites/rapidash.png",
        hasVariant: true
    },
    {
        key: 78,
        id: 79,
        name: "Slowpoke",
        types: ["Water", "Psychic"],
        img: "./img/Pokemon/079Slowpoke.webp",
        stats: [90, 65, 65, 40, 40, 15, 315],
        dexEntry: "Incredibly slow and sluggish. It is quite content to loll about without worrying about the time.",
        cry: "./cries/slowpoke.mp3",
        abilities: ["Obilvious", "Own Tempo", "Regenerator"],
        sprite: "./img/Sprites/slowpoke.png",
        hasVariant: true
    },
    {
        key: 79,
        id: 80,
        name: "Slowbro",
        types: ["Water", "Psychic"],
        img: "./img/Pokemon/080Slowbro.webp",
        stats: [95, 75, 110, 100, 80, 30, 490],
        dexEntry: "Lives lazily by the sea. If the Shellder on its tail comes off, it becomes a Slowpoke again.",
        cry: "./cries/slowbro.mp3",
        abilities: ["Obilvious", "Own Tempo", "Regenerator"],
        sprite: "./img/Sprites/slowbro.png",
        hasVariant: true
    },
    {
        key: 80,
        id: 81,
        name: "Magnemite",
        types: ["Electric", "Steel"],
        img: "./img/Pokemon/081Magnemite.webp",
        stats: [25, 35, 70, 95, 55, 45, 325],
        dexEntry: "It is hatched with the ability to defy gravity. It floats while emitting powerful electromagnetic waves.",
        cry: "./cries/magnemite.mp3",
        abilities: ["Magnetic Pull", "Sturdy", "Analytic"],
        sprite: "./img/Sprites/magnemite.png"
    },
    {
        key: 81,
        id: 82,
        name: "Magneton",
        types: ["Electric", "Steel"],
        img: "./img/Pokemon/082Magneton.webp",
        stats: [50, 60, 95, 120, 70, 70, 465],
        dexEntry: "Generates strange radio signals. It raises the temperature by 3.6 degrees Fahrenheit within 3,300 feet.",
        cry: "./cries/magneton.mp3",
        abilities: ["Magnetic Pull", "Sturdy", "Analytic"],
        sprite: "./img/Sprites/magneton.png"
    },
    {
        key: 82,
        id: 83,
        name: "Farfetch'd",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/083Farfetch'd.webp",
        stats: [52, 65, 55, 58, 62, 60, 352],
        dexEntry: "They live where reedy plants grow. Farfetch'd are rarely seen, so it's thought their numbers are decreasing.",
        cry: "./cries/farfetchd.mp3",
        abilities: ["Keen Eye", "Inner Focus", "Defiant"],
        sprite: "./img/Sprites/farfetchd.png",
        hasVariant: true
    },
    {
        key: 83,
        id: 84,
        name: "Doduo",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/084Doduo.png",
        stats: [35, 85, 45, 35, 35, 75, 310],
        dexEntry: "Its short wings make flying difficult. Instead, this Pokémon runs at high speed on developed legs.",
        cry: "./cries/doduo.mp3",
        abilities: ["Run Away", "Early Bird", "Tangled Feet"],
        sprite: "./img/Sprites/doduo.png"
    },
    {
        key: 84,
        id: 85,
        name: "Dodrio",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/085Dodrio.png",
        stats: [60, 110, 70, 60, 60, 100, 460],
        dexEntry: "One of Doduo's two heads splits to form a unique species. It runs close to 40 mph in prairies.",
        cry: "./cries/dodrio.mp3",
        abilities: ["Run Away", "Early Bird", "Tangled Feet"],
        sprite: "./img/Sprites/dodrio.png"
    },
    {
        key: 85,
        id: 86,
        name: "Seel",
        types: ["Water", "Ice"],
        img: "./img/Pokemon/086Seel.png",
        stats: [65, 45, 55, 45, 70, 45, 325],
        dexEntry: "Loves freezing-cold conditions. Relishes swimming in a frigid climate of around 14 degrees Fahrenheit.",
        cry: "./cries/seel.mp3",
        abilities: ["Thick Fat", "Hydration", "Ice Body"],
        sprite: "./img/Sprites/seel.png"
    },
    {
        key: 86,
        id: 87,
        name: "Dewgong",
        types: ["Water", "Ice"],
        img: "./img/Pokemon/087Dewgong.png",
        stats: [90, 70, 80, 70, 95, 70, 475],
        dexEntry: "Its entire body is a snowy white. Unharmed by even intense cold, it swims powerfully in icy waters.",
        cry: "./cries/dewgong.mp3",
        abilities: ["Thick Fat", "Hydration", "Ice Body"],
        sprite: "./img/Sprites/dewgong.png"
    },
    {
        key: 87,
        id: 88,
        name: "Grimer",
        types: ["Poison"],
        img: "./img/Pokemon/088Grimer.png",
        stats: [80, 80, 50, 40, 50, 25, 325],
        dexEntry: "Made of congealed sludge. It smells too putrid to touch. Even weeds won't grow in its path.",
        cry: "./cries/grimer.mp3",
        abilities: ["Stench", "Sticky Hold", "Poison Touch"],
        sprite: "./img/Sprites/grimer.png",
        hasVariant: true
    },
    {
        key: 88,
        id: 89,
        name: "Muk",
        types: ["Poison"],
        img: "./img/Pokemon/089Muk.png",
        stats: [105, 105, 75, 65, 100, 50, 500],
        dexEntry: "Smells so awful, it can cause fainting. Through degeneration of its nose, it lost its sense of smell.",
        cry: "./cries/muk.mp3",
        abilities: ["Stench", "Sticky Hold", "Poison Touch"],
        sprite: "./img/Sprites/muk.png",
        hasVariant: true
    },
    {
        key: 89,
        id: 90,
        name: "Shellder",
        types: ["Water", "Ice"],
        img: "./img/Pokemon/090Shellder.png",
        stats: [30, 65, 100, 45, 25, 40, 305],
        dexEntry: "The shell can withstand any attack. However, when it is open, the tender body is exposed.",
        cry: "./cries/shellder.mp3",
        abilities: ["Shell Armor", "Skill Link", "Overcoat"],
        sprite: "./img/Sprites/shellder.png"
    },
    {
        key: 90,
        id: 91,
        name: "Cloyster",
        types: ["Water", "Ice"],
        img: "./img/Pokemon/091Cloyster.png",
        stats: [50, 95, 180, 85, 45, 70, 525],
        dexEntry: "For protection, it uses its harder-than-diamonds shell. It also shoots spikes from the shell.",
        cry: "./cries/cloyster.mp3",
        abilities: ["Shell Armor", "Skill Link", "Overcoat"],
        sprite: "./img/Sprites/cloyster.png"
    },
    {
        key: 91,
        id: 92,
        name: "Gastly",
        types: ["Ghost", "Poison"],
        img: "./img/Pokemon/092Gastly.png",
        stats: [30, 35, 30, 100, 35, 80, 310],
        dexEntry: "Said to appear in decrepit, deserted buildings. It has no real shape, as it appears to be made of a gas.",
        cry: "./cries/gastly.mp3",
        abilities: ["Levitate"],
        sprite: "./img/Sprites/gastly.png"
    },
    {
        key: 92,
        id: 93,
        name: "Haunter",
        types: ["Ghost", "Poison"],
        img: "./img/Pokemon/093Haunter.webp",
        stats: [45, 50, 45, 115, 55, 95, 405],
        dexEntry: "By licking, it saps the victim's life. It causes shaking that won't stop until the victim's demise.",
        cry: "./cries/haunter.mp3",
        abilities: ["Levitate"],
        sprite: "./img/Sprites/haunter.png"
    },
    {
        key: 93,
        id: 94,
        name: "Gengar",
        types: ["Ghost", "Poison"],
        img: "./img/Pokemon/094Gengar.webp",
        stats: [60, 65, 60, 130, 75, 110, 500],
        dexEntry: "A Gengar is close by if you feel a sudden chill. It may be trying to lay a curse on you.",
        cry: "./cries/gengar.mp3",
        abilities: ["Cursed Body"],
        sprite: "./img/Sprites/gengar.png",
        hasVariant: true
    },
    {
        key: 94,
        id: 95,
        name: "Onix",
        types: ["Rock", "Ground"],
        img: "./img/Pokemon/095Onix.webp",
        stats: [35, 45, 160, 30, 45, 70, 385],
        dexEntry: "Burrows at high speed in search of food. The tunnels it leaves are used as homes by Diglett.",
        cry: "./cries/onix.mp3",
        abilities: ["Rock Head", "Sturdy", "Weak Armor"],
        sprite: "./img/Sprites/onix.png"
    },
    {
        key: 95,
        id: 96,
        name: "Drowzee",
        types: ["Psychic"],
        img: "./img/Pokemon/096Drowzee.png",
        stats: [60, 48, 45, 43, 90, 42, 328],
        dexEntry: "If you sleep by it all the time, it will sometimes show you dreams it had eaten in the past.",
        cry: "./cries/drowzee.mp3",
        abilities: ["Insomnia", "Forewarn", "Inner Focus"],
        sprite: "./img/Sprites/drowzee.png"
    },
    {
        key: 96,
        id: 97,
        name: "Hypno",
        types: ["Psychic"],
        img: "./img/Pokemon/097Hypno.png",
        stats: [85, 73, 70, 73, 115, 67, 483],
        dexEntry: "Avoid eye contact if you come across one. It will try to put you to sleep by using its pendulum.",
        cry: "./cries/hypno.mp3",
        abilities: ["Insomnia", "Forewarn", "Inner Focus"],
        sprite: "./img/Sprites/hypno.png"
    },
    {
        key: 97,
        id: 98,
        name: "Krabby",
        types: ["Water"],
        img: "./img/Pokemon/098Krabby.png",
        stats: [30, 105, 90, 25, 25, 50, 325],
        dexEntry: "Its pincers are superb weapons. They sometimes break off during battle, but they grow back fast.",
        cry: "./cries/krabby.mp3",
        abilities: ["Hyper Cutter", "Shell Armor", "Sheer Force"],
        sprite: "./img/Sprites/krabby.png"
    },
    {
        key: 98,
        id: 99,
        name: "Kingler",
        types: ["Water"],
        img: "./img/Pokemon/099Kingler.webp",
        stats: [55, 130, 115, 50, 50, 75, 475],
        dexEntry: "One claw grew massively and is as hard as steel. It has 10,000-horsepower strength. However, it is too heavy.",
        cry: "./cries/kingler.mp3",
        abilities: ["Hyper Cutter", "Shell Armor", "Sheer Force"],
        sprite: "./img/Sprites/kingler.png",
        hasVariant: true
    },
    {
        key: 99,
        id: 100,
        name: "Voltorb",
        types: ["Electric"],
        img: "./img/Pokemon/100Voltorb.png",
        stats: [40, 30, 50, 55, 55, 100, 330],
        dexEntry: "	It is said to camouflage itself as a Poké Ball. It will self-destruct with very little stimulus.",
        cry: "./cries/voltorb.mp3",
        abilities: ["Soundproof", "Static", "Aftermath"],
        sprite: "./img/Sprites/voltorb.png"
    },
    {
        key: 100,
        id: 101,
        name: "Electrode",
        types: ["Electric"],
        img: "./img/Pokemon/101Electrode.webp",
        stats: [60, 50, 70, 80, 80, 140, 480],
        dexEntry: "Stores electrical energy inside its body. Even the slightest shock could trigger a huge explosion.",
        cry: "./cries/electrode.mp3",
        abilities: ["Soundproof", "Static", "Aftermath"],
        sprite: "./img/Sprites/electrode.png"
    },
    {
        key: 101,
        id: 102,
        name: "Exeggcute",
        types: ["Grass", "Psychic"],
        img: "./img/Pokemon/102Exeggcute.png",
        stats: [60, 40, 80, 60, 45, 40, 325],
        dexEntry: "The heads attract each other and spin around. There must be six heads for it to maintain balance.",
        cry: "./cries/exeggcute.mp3",
        abilities: ["Chlorophyll", "Harvest"],
        sprite: "./img/Sprites/exeggcute.png"
    },
    {
        key: 102,
        id: 103,
        name: "Exeggutor",
        types: ["Grass", "Psychic"],
        img: "./img/Pokemon/103Exeggutor.png",
        stats: [95, 95, 85, 125, 75, 55, 530],
        dexEntry: "Its cries are very noisy. This is because each of the three heads thinks about whatever it likes.",
        cry: "./cries/exeggutor.mp3",
        abilities: ["Chlorophyll", "Harvest"],
        sprite: "./img/Sprites/exeggutor.png",
        hasVariant: true
    },
    {
        key: 103,
        id: 104,
        name: "Cubone",
        types: ["Ground"],
        img: "./img/Pokemon/104Cubone.webp",
        stats: [50, 50, 95, 40, 50, 35, 320],
        dexEntry: "Wears the skull of its deceased mother. Its cries echo inside the skull and come out as a sad melody.",
        cry: "./cries/cubone.mp3",
        abilities: ["Rock Head", "Lightning Rod", "Battle Armor"],
        sprite: "./img/Sprites/cubone.png"
    },
    {
        key: 104,
        id: 105,
        name: "Marowak",
        types: ["Ground"],
        img: "./img/Pokemon/105Marowak.webp",
        stats: [60, 80, 110, 50, 80, 45, 425],
        dexEntry: "Small and weak, this Pokémon is adept with its bone club. It has grown more vicious over the ages.",
        cry: "./cries/marowak.mp3",
        abilities: ["Rock Head", "Lightning Rod", "Battle Armor"],
        sprite: "./img/Sprites/marowak.png",
        hasVariant: true
    },
    {
        key: 105,
        id: 106,
        name: "Hitmonlee",
        types: ["Fighting"],
        img: "./img/Pokemon/106Hitmonlee.webp",
        stats: [50, 120, 53, 35, 110, 87, 455],
        dexEntry: "When kicking, the sole of its foot turns as hard as a diamond on impact and destroys its enemy.",
        cry: "./cries/hitmonlee.mp3",
        abilities: ["Limber", "Reckless", "Unburden"],
        sprite: "./img/Sprites/hitmonlee.png"
    },
    {
        key: 106,
        id: 107,
        name: "Hitmonchan",
        types: ["Fighting"],
        img: "./img/Pokemon/107Hitmonchan.webp",
        stats: [50, 105, 79, 35, 110, 76, 455],
        dexEntry: "Punches in corkscrew fashion. It can punch its way through a concrete wall like a drill.",
        cry: "./cries/hitmonchan.mp3",
        abilities: ["Keen Eye", "Iron Fist", "Inner Focus"],
        sprite: "./img/Sprites/hitmonchan.png"
    },
    {
        key: 107,
        id: 108,
        name: "Lickitung",
        types: ["Normal"],
        img: "./img/Pokemon/108Lickitung.webp",
        stats: [90, 55, 75, 60, 75, 30, 385],
        dexEntry: "Its tongue spans almost seven feet and moves more freely than its forelegs. Its licks can cause paralysis.",
        cry: "./cries/lickitung.mp3",
        abilities: ["Own Tempo", "Oblivious", "Cloud Nine"],
        sprite: "./img/Sprites/lickitung.png"
    },
    {
        key: 108,
        id: 109,
        name: "Koffing",
        types: ["Poison"],
        img: "./img/Pokemon/109Koffing.png",
        stats: [40, 65, 95, 60, 45, 35, 340],
        dexEntry: "In hot places, its internal gases could expand and explode without any warning. Be very careful!",
        cry: "./cries/koffing.mp3",
        abilities: ["Levitate", "Neutralizing Gas", "Stench"],
        sprite: "./img/Sprites/koffing.png"
    },

    {
        key: 109,
        id: 110,
        name: "Weezing",
        types: ["Poison"],
        img: "./img/Pokemon/110Weezing.png",
        stats: [65, 90, 120, 85, 70, 60, 490],
        dexEntry: "This Pokémon lives and grows by absorbing poison gas, dust, and germs that exist inside garbage.",
        cry: "./cries/weezing.mp3",
        abilities: ["Levitate", "Neutralizing Gas", "Stench"],
        sprite: "./img/Sprites/weezing.png",
        hasVariant: true
    },{
        key: 110,
        id: 111,
        name: "Rhyhorn",
        types: ["Rock", "Ground"],
        img: "./img/Pokemon/111Rhyhorn.webp",
        stats: [80, 85, 95, 30, 30, 25, 345],
        dexEntry: "A Pokémon with a one-track mind. Once it charges, it won't stop running until it falls asleep.",
        cry: "./cries/rhyhorn.mp3",
        abilities: ["Lightning Rod", "Rock Head", "Reckless"],
        sprite: "./img/Sprites/rhyhorn.png"
    },
    {
        key: 111,
        id: 112,
        name: "Rhydon",
        types: ["Rock", "Ground"],
        img: "./img/Pokemon/112Rhydon.webp",
        stats: [105, 130, 120, 45, 45, 40, 485],
        dexEntry: "Its brain developed when it began walking on its hind legs. Its armor-like hide even repels molten lava.",
        cry: "./cries/rhydon.mp3",
        abilities: ["Lightning Rod", "Rock Head", "Reckless"],
        sprite: "./img/Sprites/rhydon.png"
    },
    {
        key: 112,
        id: 113,
        name: "Chansey",
        types: ["Normal"],
        img: "./img/Pokemon/113Chansey.webp",
        stats: [250, 5, 5, 35, 105, 50, 450],
        dexEntry: "A gentle and kindhearted Pokémon that shares its nutritious eggs if it sees an injured Pokémon.",
        cry: "./cries/chansey.mp3",
        abilities: ["Natural Cure", "Serene Grace", "Healer"],
        sprite: "./img/Sprites/chansey.png"
    },
    {
        key: 113,
        id: 114,
        name: "Tangela",
        types: ["Grass"],
        img: "./img/Pokemon/114Tangela.png",
        stats: [65, 55, 115, 100, 40, 60, 435],
        dexEntry: "Its identity is obscured by masses of thick blue vines. The vines are said to never stop growing.",
        cry: "./cries/tangela.mp3",
        abilities: ["Chlorophyll", "Leaf Guard", "Regenerator"],
        sprite: "./img/Sprites/tangela.png"
    },
    {
        key: 114,
        id: 115,
        name: "Kangaskhan",
        types: ["Normal"],
        img: "./img/Pokemon/115Kangaskhan.webp",
        stats: [105, 95, 80, 40, 80, 90, 490],
        dexEntry: "Raises its young in its belly pouch. Won't run from any fight to keep its young protected.",
        cry: "./cries/kangaskhan.mp3",
        abilities: ["Early Bird", "Scrappy", "Inner Focus"],
        sprite: "./img/Sprites/kangaskhan.png",
        hasVariant: true
    },
    {
        key: 115,
        id: 116,
        name: "Horsea",
        types: ["Water"],
        img: "./img/Pokemon/116Horsea.webp",
        stats: [30, 40, 70, 70, 25, 60, 295],
        dexEntry: "If it senses any danger, it will vigorously spray water or a special type of ink from its mouth.",
        cry: "./cries/horsea.mp3",
        abilities: ["Swift Swim", "Sniper", "Damp"],
        sprite: "./img/Sprites/horsea.png"
    },
    {
        key: 116,
        id: 117,
        name: "Seadra",
        types: ["Water"],
        img: "./img/Pokemon/117Seadra.webp",
        stats: [55, 65, 95, 95, 45, 85, 440],
        dexEntry: "Touching the back fin causes numbness. It hooks its tail to coral to stay in place while sleeping.",
        cry: "./cries/seadra.mp3",
        abilities: ["Swift Swim", "Sniper", "Damp"],
        sprite: "./img/Sprites/seadra.png"
    },
    {
        key: 117,
        id: 118,
        name: "Goldeen",
        types: ["Water"],
        img: "./img/Pokemon/118Goldeen.webp",
        stats: [45, 67, 60, 35, 50, 63, 320],
        dexEntry: "When it is time for them to lay eggs, they can be seen swimming up rivers and falls in large groups.",
        cry: "./cries/goldeen.mp3",
        abilities: ["Swift Swim", "Water Veil", "Lightning Rod"],
        sprite: "./img/Sprites/goldeen.png"
    },
    {
        key: 118,
        id: 119,
        name: "Seaking",
        types: ["Water"],
        img: "./img/Pokemon/119Seaking.png",
        stats: [80, 92, 65, 65, 80, 68, 450],
        dexEntry: "It is the male's job to make a nest by carving out boulders in a stream using the horn on its head.",
        cry: "./cries/seaking.mp3",
        abilities: ["Swift Swim", "Water Veil", "Lightning Rod"],
        sprite: "./img/Sprites/seaking.png"
    },
    {
        key: 119,
        id: 120,
        name: "Staryu",
        types: ["Water"],
        img: "./img/Pokemon/120Staryu.webp",
        stats: [30, 45, 55, 70, 55, 85, 340],
        dexEntry: "As long as the center section is unharmed, this Pokémon can grow back fully even if it is chopped to bits.",
        cry: "./cries/staryu.mp3",
        abilities: ["Illuminate", "Natural Cure", "Analytic"],
        sprite: "./img/Sprites/staryu.png"
    },
    {
        key: 120,
        id: 121,
        name: "Starmie",
        types: ["Water", "Psychic"],
        img: "./img/Pokemon/121Starmie.webp",
        stats: [60, 75, 85, 100, 85, 115, 520],
        dexEntry: "The center section is named the core. People think it is communicating when it glows in seven colors.",
        cry: "./cries/starmie.mp3",
        abilities: ["Illuminate", "Natural Cure", "Analytic"],
        sprite: "./img/Sprites/starmie.png"
    },
    {
        key: 121,
        id: 122,
        name: "Mr. Mime",
        types: ["Psychic", "Fairy"],
        img: "./img/Pokemon/122MrMime.webp",
        stats: [40, 45, 65, 100, 120, 90, 460],
        dexEntry: "Always practices its pantomime act. It makes enemies believe something exists that really doesn't.",
        cry: "./cries/mrmime.mp3",
        abilities: ["Soundproof", "Filter", "Technician"],
        sprite: "./img/Sprites/mrmime.png",
        hasVariant: true
    },
    {
        key: 122,
        id: 123,
        name: "Scyther",
        types: ["Bug", "Flying"],
        img: "./img/Pokemon/123Scyther.webp",
        stats: [70, 110, 80, 55, 80, 105, 500],
        dexEntry: "Leaps out of tall grass and slices prey with its scythes. The movement looks like that of a ninja.",
        cry: "./cries/scyther.mp3",
        abilities: ["Swarm", "Technician", "Steadfast"],
        sprite: "./img/Sprites/scyther.png"
    },
    {
        key: 123,
        id: 124,
        name: "Jynx",
        types: ["Ice", "Psychic"],
        img: "./img/Pokemon/124Jynx.webp",
        stats: [65, 50, 35, 115, 95, 95, 455],
        dexEntry: "Appears to move to a rhythm of its own, as if it were dancing. It wiggles its hips as it walks.",
        cry: "./cries/jynx.mp3",
        abilities: ["Oblivious", "Forewarn", "Dry Skin"],
        sprite: "./img/Sprites/jynx.png"
    },
    {
        key: 124,
        id: 125,
        name: "Electabuzz",
        types: ["Electric"],
        img: "./img/Pokemon/125Electabuzz.webp",
        stats: [65, 83, 57, 95, 85, 105, 490],
        dexEntry: "If a major power outage occurs, it is certain that this Pokémon has eaten electricity at a power plant.",
        cry: "./cries/electabuzz.mp3",
        abilities: ["Static", "Vital Spirit"],
        sprite: "./img/Sprites/electabuzz.png"
    },
    {
        key: 125,
        id: 126,
        name: "Magmar",
        types: ["Fire"],
        img: "./img/Pokemon/126Magmar.webp",
        stats: [65, 95, 57, 100, 85, 93, 495],
        dexEntry: "Born in an active volcano. Its body is always cloaked in flames, so it looks like a big ball of fire.",
        cry: "./cries/magmar.mp3",
        abilities: ["Flame Body", "Vital Spirit"],
        sprite: "./img/Sprites/magmar.png"
    },
    {
        key: 126,
        id: 127,
        name: "Pinsir",
        types: ["Bug"],
        img: "./img/Pokemon/127Pinsir.png",
        stats: [65, 125, 100, 55, 70, 85, 500],
        dexEntry: "Grips its prey in its pincers and squeezes hard! It can't move if it's cold, so it lives in warm places.",
        cry: "./cries/pinsir.mp3",
        abilities: ["Hyper Cutter", "Mold Breaker", "Moxie"],
        sprite: "./img/Sprites/pinsir.png",
        hasVariant: true
    },
    {
        key: 127,
        id: 128,
        name: "Tauros",
        types: ["Normal"],
        img: "./img/Pokemon/128Tauros.webp",
        stats: [75, 100, 95, 40, 70, 110, 490],
        dexEntry: "A rowdy Pokémon with a lot of stamina. Once running, it won't stop until it hits something.",
        cry: "./cries/tauros.mp3",
        abilities: ["Intimidate", "Anger Point", "Sheer Force"],
        sprite: "./img/Sprites/tauros.png"
    },
    {
        key: 128,
        id: 129,
        name: "Magikarp",
        types: ["Water"],
        img: "./img/Pokemon/129Magikarp.webp",
        stats: [20, 10, 55, 15, 20, 80, 200],
        dexEntry: "Famous for being very unreliable. It can be found swimming in seas, lakes, rivers and shallow puddles.",
        cry: "./cries/magikarp.mp3",
        abilities: ["Swift Swim", "Rattled"],
        sprite: "./img/Sprites/magikarp.png"
    },
    {
        key: 129,
        id: 130,
        name: "Gyarados",
        types: ["Water", "Flying"],
        img: "./img/Pokemon/130Gyarados.webp",
        stats: [95, 125, 79, 60, 100, 81, 540],
        dexEntry: "Brutally vicious and enormously destructive. Known for totally destroying cities in ancient times.",
        cry: "./cries/gyarados.mp3",
        abilities: ["Intimidate", "Moxie"],
        sprite: "./img/Sprites/gyarados.png",
        hasVariant: true
    },
    {
        key: 130,
        id: 131,
        name: "Lapras",
        types: ["Water", "Ice"],
        img: "./img/Pokemon/131Lapras.webp",
        stats: [130, 85, 80, 85, 95, 60, 535],
        dexEntry: "A gentle soul that can understand human speech. It can ferry people across the sea on its back.",
        cry: "./cries/lapras.mp3",
        abilities: ["Water Absorb", "Shell Armor", "Hydration"],
        sprite: "./img/Sprites/lapras.png",
        hasVariant: true
    },
    {
        key: 131,
        id: 132,
        name: "Ditto",
        types: ["Normal"],
        img: "./img/Pokemon/132Ditto.webp",
        stats: [48, 48, 48, 48, 48, 48, 288],
        dexEntry: "When it spots an enemy, its body transfigures into an almost-perfect copy of its opponent.",
        cry: "./cries/ditto.mp3",
        abilities: ["Limber", "Imposter"],
        sprite: "./img/Sprites/ditto.png"
    },
    {
        key: 132,
        id: 133,
        name: "Eevee",
        types: ["Normal"],
        img: "./img/Pokemon/133Eevee.webp",
        stats: [65, 75, 70, 65, 85, 75, 435],
        dexEntry: "It can evolve into a variety of forms. Eevee's genes are the key to solving the mysteries of Pokémon evolution.",
        cry: "./cries/eevee.mp3",
        abilities: ["Run Away", "Adaptibility", "Anticipation"],
        sprite: "./img/Sprites/eevee.png"
    },
    {
        key: 133,
        id: 134,
        name: "Vaporeon",
        types: ["Water"],
        img: "./img/Pokemon/134Vaporeon.webp",
        stats: [130, 65, 60, 110, 95, 65, 525],
        dexEntry: "Its cell structure is similar to water molecules. It melts into the water and becomes invisible.",
        cry: "./cries/vaporeon.mp3",
        abilities: ["Water Absorb", "Hydration"],
        sprite: "./img/Sprites/vaporeon.png"
    },
    {
        key: 134,
        id: 135,
        name: "Jolteon",
        types: ["Electric"],
        img: "./img/Pokemon/135Jolteon.webp",
        stats: [65, 65, 60, 110, 95, 130, 525],
        dexEntry: "A sensitive Pokémon that easily becomes sad or angry. Every time its mood changes, it charges power.",
        cry: "./cries/jolteon.mp3",
        abilities: ["Volt Absorb", "Quick Feet"],
        sprite: "./img/Sprites/jolteon.png"
    },
    {
        key: 135,
        id: 136,
        name: "Flareon",
        types: ["Fire"],
        img: "./img/Pokemon/136Flareon.webp",
        stats: [65, 130, 60, 95, 110, 65, 525],
        dexEntry: "It has a flame chamber inside its body. It inhales, then breathes out fire that is over 3,000 degrees Fahrenheit.",
        cry: "./cries/flareon.mp3",
        abilities: ["Flash Fire", "Guts"],
        sprite: "./img/Sprites/flareon.png"
    },
    {
        key: 136,
        id: 137,
        name: "Porygon",
        types: ["Normal"],
        img: "./img/Pokemon/137Porygon.webp",
        stats: [65, 60, 70, 85, 75, 40, 395],
        dexEntry: "The only Pokémon that people anticipate can fly into space. None has managed the feat yet, however.",
        cry: "./cries/porygon.mp3",
        abilities: ["Trace", "Download", "Analytic"],
        sprite: "./img/Sprites/porygon.png"
    },
    {
        key: 137,
        id: 138,
        name: "Omanyte",
        types: ["Rock", "Water"],
        img: "./img/Pokemon/138Omanyte.webp",
        stats: [35, 40, 100, 90, 55, 35, 355],
        dexEntry: "An ancient Pokémon that was recovered from a fossil. It swam by cleverly twisting its 10 tentacles about.",
        cry: "./cries/omanyte.mp3",
        abilities: ["Swift Swim", "Shell Armor", "Weak Armor"],
        sprite: "./img/Sprites/omanyte.png"
    },
    {
        key: 138,
        id: 139,
        name: "Omastar",
        types: ["Rock", "Water"],
        img: "./img/Pokemon/139Omastar.webp",
        stats: [70, 60, 125, 115, 70, 55, 495],
        dexEntry: "Its sharp beak rings its mouth. Its shell was too big for it to move freely, so it became extinct.",
        cry: "./cries/omastar.mp3",
        abilities: ["Swift Swim", "Shell Armor", "Weak Armor"],
        sprite: "./img/Sprites/omastar.png"
    },
    {
        key: 139,
        id: 140,
        name: "Kabuto",
        types: ["Rock", "Water"],
        img: "./img/Pokemon/140Kabuto.webp",
        stats: [30, 80, 90, 55, 45, 55, 355],
        dexEntry: "A Pokémon that was recovered from a fossil. It used the eyes on its back while hiding on the seafloor.",
        cry: "./cries/kabuto.mp3",
        abilities: ["Swift Swim", "Battle Armor", "Weak Armor"],
        sprite: "./img/Sprites/kabuto.png"
    },
    {
        key: 140,
        id: 141,
        name: "Kabutops",
        types: ["Rock", "Water"],
        img: "./img/Pokemon/141Kabutops.webp",
        stats: [60, 115, 105, 65, 70, 80, 495],
        dexEntry: "A slim and fast swimmer. It sliced its prey with its sharp sickles and drank the body fluids.",
        cry: "./cries/kabutops.mp3",
        abilities: ["Swift Swim", "Battle Armor", "Weak Armor"],
        sprite: "./img/Sprites/kabutops.png"
    },
    {
        key: 141,
        id: 142,
        name: "Aerodactyl",
        types: ["Rock", "Flying"],
        img: "./img/Pokemon/142Aerodactyl.webp",
        stats: [80, 105, 65, 60, 75, 130, 515],
        dexEntry: "A savage Pokémon that died out in ancient times. It was resurrected using DNA taken from amber.",
        cry: "./cries/aerodactyl.mp3",
        abilities: ["Rock Head", "Pressure", "Unnerve"],
        sprite: "./img/Sprites/aerodactyl.png"
    },
    {
        key: 142,
        id: 143,
        name: "Snorlax",
        types: ["Normal"],
        img: "./img/Pokemon/143Snorlax.webp",
        stats: [160, 110, 65, 65, 110, 30, 540],
        dexEntry: "Will eat anything, even if the food happens to be a little moldy. It never gets an upset stomach.",
        cry: "./cries/snorlax.mp3",
        abilities: ["Immunity", "Thick Fat", "Gluttony"],
        sprite: "./img/Sprites/snorlax.png"
    },
    {
        key: 143,
        id: 144,
        name: "Articuno",
        types: ["Ice", "Flying"],
        img: "./img/Pokemon/144Articuno.webp",
        stats: [90, 85, 100, 95, 125, 85, 580],
        dexEntry: "A legendary bird Pokémon. It freezes water that is contained in winter air and makes it snow.",
        cry: "./cries/articuno.mp3",
        abilities: ["Pressure", "Snow Cloak"],
        sprite: "./img/Sprites/articuno.png",
        hasVariant: true
    },
    {
        key: 144,
        id: 145,
        name: "Zapdos",
        types: ["Electric", "Flying"],
        img: "./img/Pokemon/145Zapdos.webp",
        stats: [90, 90, 85, 125, 90, 100, 580],
        dexEntry: "	This legendary bird Pokémon is said to appear when the sky turns dark and lightning showers down.",
        cry: "./cries/zapdos.mp3",
        abilities: ["Pressure", "Static"],
        sprite: "./img/Sprites/zapdos.png",
        hasVariant: true
    },
    {
        key: 145,
        id: 146,
        name: "Moltres",
        types: ["Fire", "Flying"],
        img: "./img/Pokemon/146Moltres.webp",
        stats: [90, 100, 90, 125, 85, 90, 580],
        dexEntry: "A legendary bird Pokémon. As it flaps its flaming wings, even the night sky will turn red.",
        cry: "./cries/moltres.mp3",
        abilities: ["Pressure", "Flame Body"],
        sprite: "./img/Sprites/moltres.png",
        hasVariant: true
    },
    {
        key: 146,
        id: 147,
        name: "Dratini",
        types: ["Dragon"],
        img: "./img/Pokemon/147Dratini.webp",
        stats: [41, 64, 45, 50, 50, 50, 300],
        dexEntry: "Long thought to be a myth, this Pokémon's existence was only recently confirmed by a fisherman who caught one.",
        cry: "./cries/dratini.mp3",
        abilities: ["Shed Skin", "Marvel Scale"],
        sprite: "./img/Sprites/dratini.png"
    },
    {
        key: 147,
        id: 148,
        name: "Dragonair",
        types: ["Dragon"],
        img: "./img/Pokemon/148Dragonair.png",
        stats: [61, 84, 65, 70, 70, 70, 420],
        dexEntry: "According to a witness, its body was surrounded by a strange aura that gave it a mystical look.",
        cry: "./cries/dragonair.mp3",
        abilities: ["Shed Skin", "Marvel Scale"],
        sprite: "./img/Sprites/dragonair.png"
    },
    {
        key: 148,
        id: 149,
        name: "Dragonite",
        types: ["Dragon", "Flying"],
        img: "./img/Pokemon/149Dragonite.webp",
        stats: [91, 134, 95, 100, 100, 80, 600],
        dexEntry: "It is said that this Pokémon lives somewhere in the sea and that it flies. However, these are only rumors.",
        cry: "./cries/dragonite.mp3",
        abilities: ["Inner Focus", "Multiscale"],
        sprite: "./img/Sprites/dragonite.png"
    },
    {
        key: 149,
        id: 150,
        name: "Mewtwo",
        types: ["Psychic"],
        img: "./img/Pokemon/150Mewtwo.png",
        stats: [106, 110, 90, 154, 90, 130, 680],
        dexEntry: "Its DNA is almost the same as Mew's. However, its size and disposition are vastly different.",
        cry: "./cries/mewtwo.mp3",
        abilities: ["Pressure", "Unnerve"],
        sprite: "./img/Sprites/mewtwo.png",
        hasVariant: true
    },
    {
        key: 150,
        id: 151,
        name: "Mew",
        types: ["Psychic"],
        img: "./img/Pokemon/151Mew.png",
        stats: [100, 100, 100, 100, 100, 100, 600],
        dexEntry: "When viewed through a microscope, this Pokémon's short, fine, delicate hair can be seen.",
        cry: "./cries/mew.mp3",
        abilities: ["Synchronize"],
        sprite: "./img/Sprites/mew.png"
    }
]

export default Pokemon;