const VariantList = [
    {
        variantId: 0,
        id: 3,
        name: "Mega Venusaur",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/003Venusaur-Mega.png",
        dexEntry: "In order to support its flower, which has grown larger due to Mega Evolution, its back and legs have become stronger.",
        abilities: ["Thick Fat"]
    },
    {
        variantId: 1,
        id: 3,
        name: "G-Max Venusaur",
        types: ["Grass", "Poison"],
        img: "./img/Pokemon/003Venusaur-Gigantamax.png",
        dexEntry: "Huge amounts of pollen burst from it with the force of a volcanic eruption. Breathing in too much of the pollen can cause fainting.",
        abilities: ["Overgrow", "Chlorophyll"]
    },
    {   
        variantId: 2,
        id: 6,
        name: "Mega Charizard X",
        types: ["Fire", "Dragon"],
        img: "./img/Pokemon/006Charizard-Mega_X.png",
        dexEntry: "The overwhelming power that fills its entire body causes it to turn black and creates intense blue flames.",
        abilities: ["Tough Claws"]
        
    },
    {   
        variantId: 3,
        id: 6,
        name: "Mega Charizard Y",
        types: ["Fire", "Flying"],
        img: "./img/Pokemon/006Charizard-Mega_Y.png",
        dexEntry: "Its bond with its Trainer is the source of its power. It boasts speed and maneuverability greater than that of a jet fighter.",
        abilities: ["Drought"]
        
    },
    {   
        variantId: 4,
        id: 6,
        name: "G-Max Charizard",
        types: ["Fire", "Flying"],
        img: "./img/Pokemon/006Charizard-Gigantamax.webp",
        dexEntry: "The flame inside its body burns hotter than 3,600 degrees Fahrenheit. When Charizard roars, that temperature climbs even higher.",
        abilities: ["Blaze", "Solar Power"]
        
    },
    {
        variantId: 5,
        id: 9,
        name: "Mega Blastoise",
        types: ["Water"],
        img: "./img/Pokemon/009Blastoise-Mega.png",
        dexEntry: "The cannon on its back is as powerful as a tank gun. Its tough legs and back enable it to withstand the recoil from firing the cannon.",
        abilities: ["Mega Launcher"],
    },
    {
        variantId: 6,
        id: 9,
        name: "G-Max Blastoise",
        types: ["Water"],
        img: "./img/Pokemon/009Blastoise-Gigantamax.webp",
        dexEntry: "Water fired from this Pokémon's central main cannon has enough power to blast a hole into a mountain.",
        abilities: ["Torrent", "Rain Dish"],
    },
    {
        variantId: 7,
        id: 12,
        name: "G-Max Butterfree",
        types: ["Bug", "Flying"],
        img: "./img/Pokemon/012Butterfree-Gigantamax.webp",
        dexEntry: "Once it has opponents trapped in a tornado that could blow away a 10-ton truck, it finishes them off with its poisonous scales.",
        abilities: ["Compound Eyes", "Tinted Lens"],
    },
    {
        variantId: 8,
        id: 15,
        name: "Mega Beedrill",
        types: ["Bug", "Poison"],
        img: "./img/Pokemon/015Beedrill-Mega.png",
        dexEntry: "Its legs have become poison stingers. It stabs its prey repeatedly with the stingers on its limbs, dealing the final blow with the stinger on its rear.",
        abilities: ["Adaptability"],
    },
    {
        variantId: 9,
        id: 18,
        name: "Mega Pidgeot",
        types: ["Normal", "Flying"],
        img: "./img/Pokemon/018Pidgeot-Mega.png",
        dexEntry: "With its muscular strength now greatly increased, it can fly continuously for two weeks without resting.",
        abilities: ["No Guard"],
    },
    {
        variantId: 10,
        id: 19,
        name: "Alolan Rattata",
        types: ["Dark", "Normal"],
        img: "./img/Pokemon/019Rattata-Alola.png",
        dexEntry: "Its whiskers provide it with a keen sense of smell, enabling it to pick up the scent of hidden food and locate it instantly.",
        abilities: ["Gluttony", "Hustle", "Thick Fat"],
    },
    {
        variantId: 11,
        id: 20,
        name: "Alolan Raticate",
        types: ["Dark", "Normal"],
        img: "./img/Pokemon/020Raticate-Alola.png",
        dexEntry: "It makes its Rattata underlings gather food for it, dining solely on the most nutritious and delicious fare.",
        abilities: ["Gluttony", "Hustle", "Thick Fat"],
    },
    {
        variantId: 12,
        id: 25,
        name: "G-Max Pikachu",
        types: ["Electric"],
        img: "./img/Pokemon/025Pikachu-Gigantamax.webp",
        dexEntry: "When it smashes its opponents with its bolt-shaped tail, it delivers a surge of electricity equivalent to a lightning strike.",
        abilities: ["Static", "Lightning Rod"],
    },
    {
        variantId: 13,
        id: 26,
        name: "Alolan Raichu",
        types: ["Electric", "Psychic"],
        img: "./img/Pokemon/026Raichu-Alola.png",
        dexEntry: "It loves pancakes prepared with a secret Alolan recipe. Some wonder whether that recipe holds the key to this Pokémon's evolution.",
        abilities: ["Surge Surfer"],
    },
    {
        variantId: 14,
        id: 27,
        name: "Alolan Sandshrew",
        types: ["Ice", "Steel"],
        img: "./img/Pokemon/027Sandshrew-Alola.png",
        dexEntry: "Its ice-covered body lets it slide across the ground with bullet-like speed, sending its enemies flying when it hits them.",
        abilities: ["Snow Cloak", "Slush Rush"],
    },
    {
        variantId: 15,
        id: 28,
        name: "Alolan Sandslash",
        types: ["Ice", "Steel"],
        img: "./img/Pokemon/028Sandslash-Alola.png",
        dexEntry: "This is Sandslash's form after adaptation to a frigid environment. The cold air emitted by its body sharpens its icy spikes.",
        abilities: ["Snow Cloak", "Slush Rush"],
    },
    {
        variantId: 16,
        id: 37,
        name: "Alolan Vulpix",
        types: ["Ice"],
        img: "./img/Pokemon/037Vulpix-Alola.png",
        dexEntry: "	It looks like snow come to life, and the breath it exhales is –58 degrees Fahrenheit. Another name for it is Keokeo.",
        abilities: ["Snow Cloak", "Snow Warning"],
    },
    {
        variantId: 17,
        id: 38,
        name: "Alolan Ninetales",
        types: ["Ice", "Fairy"],
        img: "./img/Pokemon/038Ninetales-Alola.png",
        dexEntry: "It lives on mountains perpetually covered in snow and is revered as a deity incarnate. It appears draped in a blizzard.",
        abilities: ["Snow Cloak", "Snow Warning"],
    },
    {
        variantId: 18,
        id: 50,
        name: "Alolan Diglett",
        types: ["Ground", "Steel"],
        img: "./img/Pokemon/050Diglett-Alola.png",
        dexEntry: "	After living in soil with high iron content for some time, three steel whiskers sprouted from the top of its head.",
        abilities: ["Sand Veil", "Tangling Hair", "Sand Force"],
    },
    {
        variantId: 19,
        id: 51,
        name: "Alolan Dugtrio",
        types: ["Ground", "Steel"],
        img: "./img/Pokemon/051Dugtrio-Alola.png",
        dexEntry: "	They're referred to as triplets, but they're not identical–the metallic elements in their bodies differ slightly. The proof shows in their whiskers!",
        abilities: ["Sand Veil", "Tangling Hair", "Sand Force"],
    },
    {
        variantId: 20,
        id: 52,
        name: "Alolan Meowth",
        types: ["Dark"],
        img: "./img/Pokemon/052Meowth-Alola.png",
        dexEntry: "Highly intelligent and prideful, it's famously difficult to handle–but that's also a reason for its popularity.",
        abilities: ["Pickup", "Technician", "Rattled"],
    },
    {
        variantId: 21,
        id: 52,
        name: "Galarian Meowth",
        types: ["Steel"],
        img: "./img/Pokemon/052Meowth-Galar.png",
        dexEntry: "These daring Pokémon have coins on their foreheads. Darker coins are harder, and harder coins garner more respect among Meowth.",
        abilities: ["Pickup", "Tough Claws", "Unnerve"],
    },
    {
        variantId: 22,
        id: 52,
        name: "G-Max Meowth",
        types: ["Normal"],
        img: "./img/Pokemon/052Meowth-Gigantamax.png",
        dexEntry: "Its body has grown incredibly long and the coin on its forehead has grown incredibly large—all thanks to Gigantamax power.",
        abilities: ["Pickup", "Technician", "Unnerve"], 
    },
    {
        variantId: 23,
        id: 53,
        name: "Alolan Persian",
        types: ["Dark"],
        img: "./img/Pokemon/053Persian-Alola.png",
        dexEntry: "	It has the classiest coat. The rippling of its fur in the heat of battle has a beauty all its own.",
        abilities: ["Fur Coat", "Technician", "Rattled"],
    },
    {
        variantId: 24,
        id: 65,
        name: "Mega Alakazam",
        types: ["Psychic"],
        img: "./img/Pokemon/065Alakazam-Mega.png",
        dexEntry: "It's adept at precognition. When attacks completely miss Alakazam, that's because it's seeing the future.",
        abilities: ["Trace"],
    },
    {
        variantId: 25,
        id: 68,
        name: "G-Max Machamp",
        types: ["Fighting"],
        img: "./img/Pokemon/068Machamp-Gigantamax.webp",
        dexEntry: "One of these Pokémon once used its immeasurable strength to lift a large ship that was in trouble. It then carried the ship to port.",
        abilities: ["Guts", "No Guard", "Steadfast"],
    },
    {
        variantId: 26,
        id: 74,
        name: "Alolan Geodude",
        types: ["Rock", "Electric"],
        img: "./img/Pokemon/074Geodude-Alola.png",
        dexEntry: "Its stone head is imbued with electricity and magnetism. If you carelessly step on one, you'll be in for a painful shock.",
        abilities: ["Magnet Pull", "Sturdy", "Galvanize"],
    },
    {
        variantId: 27,
        id: 74,
        name: "Alolan Graveler",
        types: ["Rock", "Electric"],
        img: "./img/Pokemon/075Graveler-Alola.png",
        dexEntry: "When it comes rolling down a mountain path, anything in its way gets zapped by electricity and sent flying.",
        abilities: ["Magnet Pull", "Sturdy", "Galvanize"],
    },
    {
        variantId: 28,
        id: 74,
        name: "Alolan Golem",
        types: ["Rock", "Electric"],
        img: "./img/Pokemon/076Golem-Alola.png",
        dexEntry: "It uses magnetism to accelerate and fire off rocks tinged with electricity. Even if it doesn't score a direct hit, the jolt of electricity will do the job.",
        abilities: ["Magnet Pull", "Sturdy", "Galvanize"],
    },
    {
        variantId: 29,
        id: 77,
        name: "Galarian Ponyta",
        types: ["Psychic"],
        img: "./img/Pokemon/077Ponyta-Galar.png",
        dexEntry: "This Pokémon will look into your eyes and read the contents of your heart. If it finds evil there, it promptly hides away.",
        abilities: ["Run Away", "Pastel Veil", "Anticipation"],
    },
    {
        variantId: 30,
        id: 78,
        name: "Galarian Rapidash",
        types: ["Psychic", "Fairy"],
        img: "./img/Pokemon/078Rapidash-Galar.png",
        dexEntry: "Brave and prideful, this Pokémon dashes airily through the forest, its steps aided by the psychic power stored in the fur on its fetlocks.",
        abilities: ["Run Away", "Pastel Veil", "Anticipation"],
    },
    {
        variantId: 31,
        id: 79,
        name: "Galarian Slowpoke",
        types: ["Psychic"],
        img: "./img/Pokemon/079Slowpoke-Galar.png",
        dexEntry: "Because Galarian Slowpoke eat the seeds of a plant that grows only in Galar, their tails have developed a spicy flavor.",
        abilities: ["Gluttony", "Own Tempo", "Regenerator"],
    },
    {
        variantId: 32,
        id: 80,
        name: "Mega Slowbro",
        types: ["Water", "Psychic"],
        img: "./img/Pokemon/080Slowbro-Mega.png",
        dexEntry: "Under the influence of Shellder's digestive fluids, Slowpoke has awakened, gaining a great deal of power–and a little motivation to boot.",
        abilities: ["Shell Armor"],
    },
    {
        variantId: 33,
        id: 80,
        name: "Galarian Slowbro",
        types: ["Poison", "Psychic"],
        img: "./img/Pokemon/080Slowbro-Galar.png",
        dexEntry: "If this Pokémon squeezes the tongue of the Shellder biting it, the Shellder will launch a toxic liquid from the tip of its shell.",
        abilities: ["Gluttony", "Own Tempo", "Regenerator"],
    },
    {
        variantId: 34,
        id: 83,
        name: "Galarian Farfetch'd",
        types: ["Fighting"],
        img: "./img/Pokemon/083Farfetch'd-Galar.webp",
        dexEntry: "The stalks of leeks are thicker and longer in the Galar region. Farfetch'd that adapted to these stalks took on a unique form.",
        abilities: ["Steadfast", "Scrappy"],
    },
    {
        variantId: 35,
        id: 88,
        name: "Alolan Grimer",
        types: ["Poison", "Dark"],
        img: "./img/Pokemon/088Grimer-Alola.png",
        dexEntry: "It has a passion for trash above all else, speedily digesting it and creating brilliant crystals of sparkling poison.",
        abilities: ["Poison Touch", "Gluttony", "Power of Alchemy"],
    },
    {
        variantId: 36,
        id: 88,
        name: "Alolan Muk",
        types: ["Poison", "Dark"],
        img: "./img/Pokemon/089Muk-Alola.png",
        dexEntry: "Muk's coloration becomes increasingly vivid the more it feasts on its favorite dish–trash.",
        abilities: ["Poison Touch", "Gluttony", "Power of Alchemy"],
    },
    {
        variantId: 37,
        id: 94,
        name: "Mega Gengar",
        types: ["Ghost", "Poison"],
        img: "./img/Pokemon/094Gengar-Mega.png",
        dexEntry: "It can pass through other dimensions and can appear anywhere. It caused a stir one time when it stuck just one leg out of a wall.",
        abilities: ["Shadow Tag"],
    },
    {
        variantId: 38,
        id: 94,
        name: "G-Max Gengar",
        types: ["Ghost", "Poison"],
        img: "./img/Pokemon/094Gengar-Gigantamax.webp",
        dexEntry: "	It lays traps, hoping to steal the lives of those it catches. If you stand in front of its mouth, you'll hear your loved ones' voices calling out to you.",
        abilities: ["Cursed Body"],
    },
    {
        variantId: 39,
        id: 99,
        name: "G-Max Kingler",
        types: ["Water"],
        img: "./img/Pokemon/099Kingler-Gigantamax.webp",
        dexEntry: "The bubbles it spews out are strongly alkaline. Any opponents hit by them will have their bodies quickly melted away.",
        abilities: ["Hyper Cutter", "Shell Armor", "Sheer Force"],
    },
    {
        variantId: 40,
        id: 103,
        name: "Alolan Exeggutor",
        types: ["Grass", "Dragon"],
        img: "./img/Pokemon/103Exeggutor-Alola.png",
        dexEntry: "	The strong sunlight of the Alola region has awakened the power hidden within Exeggcute. This is the result.",
        abilities: ["Frisk", "Harvest"],
    },
    {
        variantId: 41,
        id: 105,
        name: "Alolan Marowak",
        types: ["Fire", "Ghost"],
        img: "./img/Pokemon/105Marowak-Alola.png",
        dexEntry: "It has transformed the spirit of its dear departed mother into flames, and tonight it will once again dance in mourning of others of its kind.",
        abilities: ["Cursed Body", "Lightning Rod", "Rock Head"],
    },
    {
        variantId: 42,
        id: 110,
        name: "Galarian Weezing",
        types: ["Poison", "Fairy"],
        img: "./img/Pokemon/110Weezing-Galar.webp",
        dexEntry: "	Long ago, during a time when droves of factories fouled the air with pollution, Weezing changed into this form for some reason.",
        abilities: ["Levitate", "Neutralizing Gas", "Misty Surge"],
    },
    {
        variantId: 43,
        id: 115,
        name: "Mega Kangaskhan",
        types: ["Normal"],
        img: "./img/Pokemon/115Kangaskhan-Mega.png",
        dexEntry: "Its child has grown rapidly, thanks to the energy of Mega Evolution. Mother and child show their harmonious teamwork in battle.",
        abilities: ["Parental Bond"],
    },
    {
        variantId: 44,
        id: 122,
        name: "Galarian Mr. Mime",
        types: ["Ice", "Psychic"],
        img: "./img/Pokemon/122Mr.webp",
        dexEntry: "It can radiate chilliness from the bottoms of its feet. It'll spend the whole day tap-dancing on a frozen floor.",
        abilities: ["Vital Spirit", "Screen Cleaner", "Ice Body"],
    },
    {
        variantId: 45,
        id: 127,
        name: "Mega Pinsir",
        types: ["Bug", "Flying"],
        img: "./img/Pokemon/127Pinsir.png",
        dexEntry: "With its vaunted horns, it can lift an opponent 10 times heavier than itself and fly about with ease.",
        abilities: ["Aerilate"],
    },
    {
        variantId: 46,
        id: 130,
        name: "Mega Gyarados",
        types: ["Water", "Dark"],
        img: "./img/Pokemon/130Gyarados-Mega.png",
        dexEntry: "Although it obeys its instinctive drive to destroy everything within its reach, it will respond to orders from a Trainer it truly trusts.",
        abilities: ["Mold Breaker"],  
    },
    {
        variantId: 47,
        id: 131,
        name: "G-max Lapras",
        types: ["Water", "Ice"],
        img: "./img/Pokemon/131Lapras-Gigantamax.webp",
        dexEntry: "It surrounds itself with a huge ring of gathered ice particles. It uses the ring to smash any icebergs that might impede its graceful swimming.",
        abilities: ["Water Absorb", "Shell Armor", "Hydration"],
    },
    {
        variantId: 48,
        id: 142,
        name: "Mega Aerodactyl",
        types: ["Rock", "Flying"],
        img: "./img/Pokemon/142Aerodactyl-Mega.png",
        dexEntry: "The power of Mega Evolution has completely restored its genes. The rocks on its body are harder than diamond.",
        abilities: ["Tough Claws"],
    },
    {
        variantId: 49,
        id: 144,
        name: "Galarian Articuno",
        types: ["Psychic", "Flying"],
        img: "./img/Pokemon/144Articuno-Galar.png",
        dexEntry: "Known as Articuno, this Pokémon fires beams that can immobilize opponents as if they had been frozen solid.",
        abilities: ["Competitive"],
    },
    {
        variantId: 50,
        id: 145,
        name: "Galarian Zapdos",
        types: ["Fighting", "Flying"],
        img: "./img/Pokemon/145Zapdos-Galar.png",
        dexEntry: "One kick from its powerful legs will pulverize a dump truck. Supposedly, this Pokémon runs through the mountains at over 180 mph.",
        abilities: ["Defiant"],
    },
    {
        variantId: 51,
        id: 146,
        name: "Moltres",
        types: ["Dark", "Flying"],
        img: "./img/Pokemon/146Moltres-Galar.png",
        dexEntry: "The sinister aura that blazes like molten fire around this Pokémon is what inspired the name Moltres.",
        abilities: ["Berserk"],
    },
    {
        variantId: 52,
        id: 150,
        name: "Mega Mewtwo X",
        types: ["Psychic", "Fighting"],
        img: "./img/Pokemon/150Mewtwo-Mega_X.png",
        dexEntry: "Psychic power has augmented its muscles. It has a grip strength of one ton and can sprint a hundred meters in two seconds flat!",
        abilities: ["Steadfast"],
    },
    {
        variantId: 53,
        id: 150,
        name: "Mewtwo",
        types: ["Psychic"],
        img: "./img/Pokemon/150Mewtwo-Mega_Y.png",
        dexEntry: "Despite its diminished size, its mental power has grown phenomenally. With a mere thought, it can smash a skyscraper to smithereens.",
        abilities: ["Insomnia"],
    }

]

export default VariantList;